version: '3'
services:
  nginx:
    build: ./nginx
    links:
        - nodejs:nodejs
    volumes:
          - ~/docker/demo/nginx:/etc/nginx
          - ~/docker:/src
    ports:
        - 80:80
        - 443:443

  nodejs:
    build: ./node
    volumes:
          - ~/docker:/src
    ports:
        - 8080:8080

  mysql:
    build: ./db
    volumes:
        - ./.data/db:/var/lib/mysql"
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: null
        MYSQL_DATABASE: docker_demo
