FROM nginx

# COPY nginx.conf nginx.conf

# FROM sshd-centos
# WORKDIR /src
# #安装wget
# RUN yum install -y  wget
# #下载并解压源码包
# RUN wget http://nginx.org/download/nginx-1.8.0.tar.gz
# RUN tar -zxvf nginx-1.8.0.tar.gz
# WORKDIR nginx-1.8.0


